CREATE DATABASE APP;

CREATE TABLE USUARIO (
	Username	VARCHAR(20)	NOT NULL,
	SeguidoresUser	INT,
	SeguindoUser	INT,
	NomeUser	VARCHAR(15)	NOT NULL,
	EmailUser	VARCHAR(40) NOT NULL,
	SenhaUser	VARCHAR(30)	NOT NULL,
	TelefoneUser	INT,
	PaisUser	VARCHAR(20)
PRIMARY KEY (Username));

CREATE TABLE SEGUIR(
	Username	VARCHAR(20)	NOT NULL,
	Username	VARCHAR(20)	NOT NULL
FOREIGN KEY(Username) REFERENCES USUARIO(Username));

CREATE TABLE LISTA(
	Username	VARCHAR(20)	NOT NULL,
	ID_Lista	INT			NOT NULL,
	NomeLista	VARCHAR(20)	NOT NULL,
	CurtidasLista	INT
PRIMARY KEY (ID_Lista)
FOREIGN KEY (Username) REFERENCES USUARIO(Username));

CREATE TABLE REVIEW(
	Username	VARCHAR(20)	NOT NULL,
	ID_Review	INT			NOT NULL,
	NotaReview	INT			NOT NULL,
	TextoReview	VARCHAR(20)
PRIMARY KEY (ID_Review)
FOREIGN KEY (Username) REFERENCES USUARIO(Username));

CREATE TABLE FILME(
	ID_Filme		INT			NOT NULL,
	TituloFilme		VARCHAR(20)	NOT NULL,
	DiretorFilme	VARCHAR(20)	NOT NULL,
	ElencoFilme		VARCHAR(20)	NOT NULL,
	GeneroFilme		VARCHAR(20)	NOT NULL,
	DataLancamento	INT			NOT NULL,
	Duracao			INT			NOT NULL,
	Classificacao	INT			NOT NULL
PRIMARY KEY (ID_Filme));

CREATE TABLE REGISTRAR(
	Username	VARCHAR(20)	NOT NULL,
	ID_Filme	INT			NOT NULL,
FOREIGN KEY (Username) REFERENCES USUARIO(Username)
FOREIGN KEY (ID_Filme) REFERENCES FILME(ID_Filme));

CREATE TABLE CURTIR_LISTA(
	Username	VARCHAR(20)	NOT NULL,
	ID_Lista	INT			NOT NULL,
PRIMARY KEY (Username, ID_Lista),
FOREIGN KEY (Username) REFERENCES USUARIO(Username)
FOREIGN KEY (ID_Lista) REFERENCES LISTA(ID_Lista));

CREATE TABLE ESTUDIO(
	ID_Estudio		INT			NOT NULL,
	NomeEstudio		VARCHAR(20)	NOT NULL,
PRIMARY KEY (ID_Estudio));

CREATE TABLE PRODUZ(
	ID_Estudio		INT		NOT NULL,
	ID_Filme		INT		NOT NULL,
PRIMARY KEY (ID_Estudio, ID_Filme),
FOREIGN KEY (ID_Estudio) REFERENCES ESTUDIO(ID_Estudio)
FOREIGN KEY (ID_Filme) REFERENCES FILME(ID_Filme));

CREATE TABLE PERTENCE_LISTA(
	ID_Lista		INT		NOT NULL,
	ID_Filme		INT		NOT NULL,
PRIMARY KEY (ID_Lista, ID_Filme),
FOREIGN KEY (ID_Lista) REFERENCES LISTA(ID_Lista)
FOREIGN KEY (ID_Filme) REFERENCES FILME(ID_Filme));

CREATE TABLE PARTICIPACAO(
	ID_Filme		INT			NOT NULL,
	ID_Participante	INT			NOT NULL,
	Funcao			VARCHAR(20) NOT NULL,
	NomePersonagem	VARCHAR(30)
PRIMARY KEY (ID_Filme, ID_Participante, Funcao),
FOREIGN KEY (ID_Filme) REFERENCES FILME(ID_Filme));








